# Generated by Django 4.2.7 on 2023-11-22 15:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_rename_serller_product_seller"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="category",
            new_name="categories",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="color",
            new_name="colors",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="size",
            new_name="sizes",
        ),
    ]
