# Generated by Django 4.2.7 on 2023-11-22 18:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_rename_category_product_categories_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ("id",), "verbose_name_plural": "Categories"},
        ),
        migrations.RenameField(
            model_name="category",
            old_name="subcategory",
            new_name="parent",
        ),
    ]
