# Generated by Django 4.2.7 on 2023-11-25 13:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_product_quantity"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="created_date",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="category",
            old_name="modified_date",
            new_name="updated_date",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="created_date",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="updated_date",
            new_name="updated_at",
        ),
    ]
