# Generated by Django 4.2.7 on 2023-11-25 13:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_verificationcode_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="email_verified",
        ),
    ]
