# Generated by Django 4.2.7 on 2023-11-24 12:23

import checkouts.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orders", "0002_remove_orderitem_price"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Checkout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("total_price", models.PositiveIntegerField()),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "order",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checkout",
                        to="orders.order",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("z", "zarinpal"), ("i", "idpay")], max_length=1
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True,
                        default=checkouts.utils.create_new_ref_number,
                        editable=False,
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[("f", "failed"), ("i", "success")], max_length=1
                    ),
                ),
                ("payment_date", models.DateTimeField(auto_now_add=True)),
                (
                    "checkout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="checkouts.checkout",
                    ),
                ),
            ],
        ),
    ]
