# Generated by Django 4.2.7 on 2023-11-24 12:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("checkouts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="checkout",
            name="total_price",
        ),
    ]
