# Generated by Django 4.2.7 on 2023-11-24 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("checkouts", "0003_alter_payment_payment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="checkout",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="checkouts.checkout",
            ),
        ),
    ]
