# Generated by Django 4.2.7 on 2023-11-25 13:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_remove_orderitem_price"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ("paid", "-updated_at")},
        ),
        migrations.RenameField(
            model_name="order",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="updated",
            new_name="updated_at",
        ),
    ]
